# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LifeFactorsWindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets

from screens.util import CalendarWidget


class Ui_main_window(object):
    def setupUi(self, main_window):
        main_window.setObjectName("main_window")
        main_window.resize(500, 600)
        main_window.setMinimumSize(QtCore.QSize(500, 600))
        main_window.setMaximumSize(QtCore.QSize(500, 600))
        self.central_widget = QtWidgets.QWidget(main_window)
        self.central_widget.setStyleSheet("")
        self.central_widget.setObjectName("central_widget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.central_widget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 501, 601))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.main_layout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.main_layout.setContentsMargins(0, 0, 0, 0)
        self.main_layout.setObjectName("main_layout")
        self.functional_layout = QtWidgets.QHBoxLayout()
        self.functional_layout.setObjectName("functional_layout")
        self.btnBack = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnBack.setMinimumSize(QtCore.QSize(60, 60))
        self.btnBack.setMaximumSize(QtCore.QSize(60, 60))
        self.btnBack.setStyleSheet("")
        self.btnBack.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/angle-left-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnBack.setIcon(icon)
        self.btnBack.setObjectName("btnBack")
        self.functional_layout.addWidget(self.btnBack)
        self.btnNext = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnNext.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnNext.sizePolicy().hasHeightForWidth())
        self.btnNext.setSizePolicy(sizePolicy)
        self.btnNext.setMinimumSize(QtCore.QSize(60, 60))
        self.btnNext.setMaximumSize(QtCore.QSize(60, 60))
        self.btnNext.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnNext.setStyleSheet("")
        self.btnNext.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/angle-right-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnNext.setIcon(icon1)
        self.btnNext.setIconSize(QtCore.QSize(16, 16))
        self.btnNext.setFlat(False)
        self.btnNext.setObjectName("btnNext")
        self.functional_layout.addWidget(self.btnNext)
        self.main_layout.addLayout(self.functional_layout, 5, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(30, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.main_layout.addItem(spacerItem, 4, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(30, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.main_layout.addItem(spacerItem1, 7, 1, 1, 1)
        self.name_layout = QtWidgets.QHBoxLayout()
        self.name_layout.setObjectName("name_layout")
        self.header = QtWidgets.QLabel(self.gridLayoutWidget)
        self.header.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.header.setFont(font)
        self.header.setObjectName("header")
        self.name_layout.addWidget(self.header)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.name_layout.addItem(spacerItem2)
        self.main_layout.addLayout(self.name_layout, 3, 1, 1, 1)
        self.navigate_layout = QtWidgets.QHBoxLayout()
        self.navigate_layout.setObjectName("navigate_layout")
        self.page_bar = QtWidgets.QProgressBar(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.page_bar.sizePolicy().hasHeightForWidth())
        self.page_bar.setSizePolicy(sizePolicy)
        self.page_bar.setMinimumSize(QtCore.QSize(0, 4))
        self.page_bar.setProperty("value", 0)
        self.page_bar.setTextVisible(False)
        self.page_bar.setObjectName("page_bar")
        self.navigate_layout.addWidget(self.page_bar)
        self.main_layout.addLayout(self.navigate_layout, 2, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(30, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.main_layout.addItem(spacerItem3, 4, 2, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(30, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.main_layout.addItem(spacerItem4, 0, 1, 1, 1)
        self.actions_layout = QtWidgets.QGridLayout()
        self.actions_layout.setObjectName("actions_layout")
        self.tip_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tip_2.setFont(font)
        self.tip_2.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.tip_2.setObjectName("tip_2")
        self.actions_layout.addWidget(self.tip_2, 4, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.actions_layout.addItem(spacerItem5, 7, 0, 1, 1)
        self.tip = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tip.setFont(font)
        self.tip.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.tip.setObjectName("tip")
        self.actions_layout.addWidget(self.tip, 0, 0, 1, 1)
        self.calendar_layout = QtWidgets.QHBoxLayout()
        self.calendar_layout.setObjectName("calendar_layout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.calendar = CalendarWidget.CalendarWidget()
        print('calendar created')
        self.calendar.setObjectName("calendar")
        self.verticalLayout.addWidget(self.calendar)
        self.calendar_layout.addLayout(self.verticalLayout)
        self.cal_btns_layout = QtWidgets.QVBoxLayout()
        self.cal_btns_layout.setObjectName("cal_btns_layout")
        self.btnFree = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnFree.sizePolicy().hasHeightForWidth())
        self.btnFree.setSizePolicy(sizePolicy)
        self.btnFree.setMinimumSize(QtCore.QSize(90, 25))
        self.btnFree.setMaximumSize(QtCore.QSize(90, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnFree.setFont(font)
        self.btnFree.setCheckable(True)
        self.btnFree.setChecked(False)
        self.btnFree.setObjectName("btnFree")
        self.cal_btns_layout.addWidget(self.btnFree)
        self.btnJob = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnJob.sizePolicy().hasHeightForWidth())
        self.btnJob.setSizePolicy(sizePolicy)
        self.btnJob.setMinimumSize(QtCore.QSize(90, 25))
        self.btnJob.setMaximumSize(QtCore.QSize(90, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnJob.setFont(font)
        self.btnJob.setCheckable(True)
        self.btnJob.setChecked(False)
        self.btnJob.setObjectName("btnJob")
        self.cal_btns_layout.addWidget(self.btnJob)
        self.btnStudy = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnStudy.sizePolicy().hasHeightForWidth())
        self.btnStudy.setSizePolicy(sizePolicy)
        self.btnStudy.setMinimumSize(QtCore.QSize(90, 25))
        self.btnStudy.setMaximumSize(QtCore.QSize(90, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnStudy.setFont(font)
        self.btnStudy.setCheckable(True)
        self.btnStudy.setChecked(False)
        self.btnStudy.setObjectName("btnStudy")
        self.cal_btns_layout.addWidget(self.btnStudy)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.cal_btns_layout.addItem(spacerItem6)
        self.calendar_layout.addLayout(self.cal_btns_layout)
        self.actions_layout.addLayout(self.calendar_layout, 6, 0, 1, 1)
        self.variables_layout = QtWidgets.QHBoxLayout()
        self.variables_layout.setObjectName("variables_layout")
        self.tip_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tip_5.sizePolicy().hasHeightForWidth())
        self.tip_5.setSizePolicy(sizePolicy)
        self.tip_5.setMinimumSize(QtCore.QSize(45, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tip_5.setFont(font)
        self.tip_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tip_5.setObjectName("tip_5")
        self.variables_layout.addWidget(self.tip_5)
        self.sleepTime_list = QtWidgets.QComboBox(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sleepTime_list.sizePolicy().hasHeightForWidth())
        self.sleepTime_list.setSizePolicy(sizePolicy)
        self.sleepTime_list.setMinimumSize(QtCore.QSize(50, 25))
        self.sleepTime_list.setMaximumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sleepTime_list.setFont(font)
        self.sleepTime_list.setObjectName("sleepTime_list")
        self.variables_layout.addWidget(self.sleepTime_list)
        self.tip_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tip_3.sizePolicy().hasHeightForWidth())
        self.tip_3.setSizePolicy(sizePolicy)
        self.tip_3.setMinimumSize(QtCore.QSize(45, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tip_3.setFont(font)
        self.tip_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tip_3.setObjectName("tip_3")
        self.variables_layout.addWidget(self.tip_3)
        self.studyTime_list = QtWidgets.QComboBox(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.studyTime_list.sizePolicy().hasHeightForWidth())
        self.studyTime_list.setSizePolicy(sizePolicy)
        self.studyTime_list.setMinimumSize(QtCore.QSize(50, 25))
        self.studyTime_list.setMaximumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.studyTime_list.setFont(font)
        self.studyTime_list.setObjectName("studyTime_list")
        self.variables_layout.addWidget(self.studyTime_list)
        self.tip_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tip_4.sizePolicy().hasHeightForWidth())
        self.tip_4.setSizePolicy(sizePolicy)
        self.tip_4.setMinimumSize(QtCore.QSize(45, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tip_4.setFont(font)
        self.tip_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tip_4.setObjectName("tip_4")
        self.variables_layout.addWidget(self.tip_4)
        self.jobTime_list = QtWidgets.QComboBox(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.jobTime_list.sizePolicy().hasHeightForWidth())
        self.jobTime_list.setSizePolicy(sizePolicy)
        self.jobTime_list.setMinimumSize(QtCore.QSize(50, 25))
        self.jobTime_list.setMaximumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.jobTime_list.setFont(font)
        self.jobTime_list.setObjectName("jobTime_list")
        self.variables_layout.addWidget(self.jobTime_list)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.variables_layout.addItem(spacerItem7)
        self.actions_layout.addLayout(self.variables_layout, 2, 0, 1, 1)
        self.main_layout.addLayout(self.actions_layout, 4, 1, 1, 1)
        main_window.setCentralWidget(self.central_widget)


        self.retranslateUi(main_window)
        QtCore.QMetaObject.connectSlotsByName(main_window)

    def retranslateUi(self, main_window):
        _translate = QtCore.QCoreApplication.translate
        main_window.setWindowTitle(_translate("main_window", "Learning program"))
        self.header.setText(_translate("main_window", "POINT YOUR LIFE FACTORS"))
        self.tip_2.setText(_translate("main_window", "Describe your current schedule"))
        self.tip.setText(_translate("main_window", "Indicate time you spend per day (hour/day):"))
        self.btnFree.setText(_translate("main_window", "Free day"))
        self.btnJob.setText(_translate("main_window", "Job day"))
        self.btnStudy.setText(_translate("main_window", "Study day"))

        self.tip_5.setText(_translate("main_window", "Sleep"))
        self.tip_3.setText(_translate("main_window", "Study"))
        self.tip_4.setText(_translate("main_window", "Job"))
