from PyQt5 import QtCore, QtGui, QtWidgets


class ScheduleScreen(object):
    def setupUi(self, main_window):
        main_window.setObjectName("main_window")
        main_window.resize(500, 600)
        main_window.setMinimumSize(QtCore.QSize(500, 600))
        main_window.setMaximumSize(QtCore.QSize(500, 600))
        self.central_widget = QtWidgets.QWidget(main_window)
        self.central_widget.setStyleSheet("")
        self.central_widget.setObjectName("central_widget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.central_widget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 501, 601))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.main_layout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.main_layout.setContentsMargins(0, 0, 0, 0)
        self.main_layout.setObjectName("main_layout")
        self.functional_layout = QtWidgets.QHBoxLayout()
        self.functional_layout.setObjectName("functional_layout")
        self.btnBack = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnBack.setMinimumSize(QtCore.QSize(60, 60))
        self.btnBack.setMaximumSize(QtCore.QSize(60, 60))
        self.btnBack.setStyleSheet("")
        self.btnBack.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/angle-left-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnBack.setIcon(icon)
        self.btnBack.setObjectName("btnBack")
        self.functional_layout.addWidget(self.btnBack)
        self.btnNext = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnNext.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnNext.sizePolicy().hasHeightForWidth())
        self.btnNext.setSizePolicy(sizePolicy)
        self.btnNext.setMinimumSize(QtCore.QSize(60, 60))
        self.btnNext.setMaximumSize(QtCore.QSize(60, 60))
        self.btnNext.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnNext.setStyleSheet("")
        self.btnNext.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/angle-right-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnNext.setIcon(icon1)
        self.btnNext.setIconSize(QtCore.QSize(16, 16))
        self.btnNext.setFlat(False)
        self.btnNext.setObjectName("btnNext")
        self.functional_layout.addWidget(self.btnNext)
        self.main_layout.addLayout(self.functional_layout, 5, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(30, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.main_layout.addItem(spacerItem, 4, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(30, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.main_layout.addItem(spacerItem1, 7, 1, 1, 1)
        self.actions_layout = QtWidgets.QGridLayout()
        self.actions_layout.setObjectName("actions_layout")
        self.tip_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tip_2.setFont(font)
        self.tip_2.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.tip_2.setObjectName("tip_2")
        self.actions_layout.addWidget(self.tip_2, 4, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.actions_layout.addItem(spacerItem2, 7, 0, 1, 1)
        self.tip = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tip.setFont(font)
        self.tip.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.tip.setObjectName("tip")
        self.actions_layout.addWidget(self.tip, 0, 0, 1, 1)
        self.calendar_layout = QtWidgets.QHBoxLayout()
        self.calendar_layout.setObjectName("calendar_layout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.calendar = QtWidgets.QWidget(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calendar.sizePolicy().hasHeightForWidth())
        self.calendar.setSizePolicy(sizePolicy)
        self.calendar.setObjectName("calendar")
        self.verticalLayout.addWidget(self.calendar)
        self.calendar_layout.addLayout(self.verticalLayout)
        self.cal_btns_layout = QtWidgets.QVBoxLayout()
        self.cal_btns_layout.setObjectName("cal_btns_layout")
        self.btnFree = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnFree.sizePolicy().hasHeightForWidth())
        self.btnFree.setSizePolicy(sizePolicy)
        self.btnFree.setMinimumSize(QtCore.QSize(90, 25))
        self.btnFree.setMaximumSize(QtCore.QSize(90, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnFree.setFont(font)
        self.btnFree.setCheckable(True)
        self.btnFree.setChecked(False)
        self.btnFree.setObjectName("btnFree")
        self.cal_btns_layout.addWidget(self.btnFree)
        self.btnLearn = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnLearn.sizePolicy().hasHeightForWidth())
        self.btnLearn.setSizePolicy(sizePolicy)
        self.btnLearn.setMinimumSize(QtCore.QSize(90, 25))
        self.btnLearn.setMaximumSize(QtCore.QSize(90, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnLearn.setFont(font)
        self.btnLearn.setCheckable(True)
        self.btnLearn.setChecked(False)
        self.btnLearn.setObjectName("btnLearn")
        self.cal_btns_layout.addWidget(self.btnLearn)
        self.btnRepeat = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnRepeat.sizePolicy().hasHeightForWidth())
        self.btnRepeat.setSizePolicy(sizePolicy)
        self.btnRepeat.setMinimumSize(QtCore.QSize(90, 25))
        self.btnRepeat.setMaximumSize(QtCore.QSize(90, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnRepeat.setFont(font)
        self.btnRepeat.setCheckable(True)
        self.btnRepeat.setChecked(False)
        self.btnRepeat.setObjectName("btnRepeat")
        self.cal_btns_layout.addWidget(self.btnRepeat)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.cal_btns_layout.addItem(spacerItem3)
        self.calendar_layout.addLayout(self.cal_btns_layout)
        self.actions_layout.addLayout(self.calendar_layout, 6, 0, 1, 1)
        self.variables_layout = QtWidgets.QHBoxLayout()
        self.variables_layout.setObjectName("variables_layout")
        self.tip_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tip_5.sizePolicy().hasHeightForWidth())
        self.tip_5.setSizePolicy(sizePolicy)
        self.tip_5.setMinimumSize(QtCore.QSize(45, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tip_5.setFont(font)
        self.tip_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tip_5.setObjectName("tip_5")
        self.variables_layout.addWidget(self.tip_5)
        self.sleepTime_list = QtWidgets.QComboBox(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sleepTime_list.sizePolicy().hasHeightForWidth())
        self.sleepTime_list.setSizePolicy(sizePolicy)
        self.sleepTime_list.setMinimumSize(QtCore.QSize(50, 25))
        self.sleepTime_list.setMaximumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sleepTime_list.setFont(font)
        self.sleepTime_list.setObjectName("sleepTime_list")
        self.sleepTime_list.addItem("")
        self.sleepTime_list.addItem("")
        self.sleepTime_list.addItem("")
        self.sleepTime_list.addItem("")
        self.sleepTime_list.addItem("")
        self.variables_layout.addWidget(self.sleepTime_list)
        self.tip_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tip_3.sizePolicy().hasHeightForWidth())
        self.tip_3.setSizePolicy(sizePolicy)
        self.tip_3.setMinimumSize(QtCore.QSize(45, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tip_3.setFont(font)
        self.tip_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tip_3.setObjectName("tip_3")
        self.variables_layout.addWidget(self.tip_3)
        self.learnTime_list = QtWidgets.QComboBox(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.learnTime_list.sizePolicy().hasHeightForWidth())
        self.learnTime_list.setSizePolicy(sizePolicy)
        self.learnTime_list.setMinimumSize(QtCore.QSize(50, 25))
        self.learnTime_list.setMaximumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.learnTime_list.setFont(font)
        self.learnTime_list.setObjectName("learnTime_list")
        self.learnTime_list.addItem("")
        self.learnTime_list.addItem("")
        self.learnTime_list.addItem("")
        self.learnTime_list.addItem("")
        self.variables_layout.addWidget(self.learnTime_list)
        self.tip_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tip_4.sizePolicy().hasHeightForWidth())
        self.tip_4.setSizePolicy(sizePolicy)
        self.tip_4.setMinimumSize(QtCore.QSize(45, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tip_4.setFont(font)
        self.tip_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tip_4.setObjectName("tip_4")
        self.variables_layout.addWidget(self.tip_4)
        self.repeatTime_list = QtWidgets.QComboBox(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.repeatTime_list.sizePolicy().hasHeightForWidth())
        self.repeatTime_list.setSizePolicy(sizePolicy)
        self.repeatTime_list.setMinimumSize(QtCore.QSize(50, 25))
        self.repeatTime_list.setMaximumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.repeatTime_list.setFont(font)
        self.repeatTime_list.setObjectName("repeatTime_list")
        self.repeatTime_list.addItem("")
        self.repeatTime_list.addItem("")
        self.repeatTime_list.addItem("")
        self.repeatTime_list.addItem("")
        self.variables_layout.addWidget(self.repeatTime_list)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.variables_layout.addItem(spacerItem4)
        self.actions_layout.addLayout(self.variables_layout, 2, 0, 1, 1)
        self.main_layout.addLayout(self.actions_layout, 4, 1, 1, 1)
        self.name_layout = QtWidgets.QHBoxLayout()
        self.name_layout.setObjectName("name_layout")
        self.header = QtWidgets.QLabel(self.gridLayoutWidget)
        self.header.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.header.setFont(font)
        self.header.setObjectName("header")
        self.name_layout.addWidget(self.header)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.name_layout.addItem(spacerItem5)
        self.main_layout.addLayout(self.name_layout, 3, 1, 1, 1)
        self.navigate_layout = QtWidgets.QHBoxLayout()
        self.navigate_layout.setObjectName("navigate_layout")
        self.page_bar = QtWidgets.QProgressBar(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.page_bar.sizePolicy().hasHeightForWidth())
        self.page_bar.setSizePolicy(sizePolicy)
        self.page_bar.setMinimumSize(QtCore.QSize(0, 4))
        self.page_bar.setProperty("value", 0)
        self.page_bar.setTextVisible(False)
        self.page_bar.setObjectName("page_bar")
        self.navigate_layout.addWidget(self.page_bar)
        self.main_layout.addLayout(self.navigate_layout, 2, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(30, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.main_layout.addItem(spacerItem6, 4, 2, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(30, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.main_layout.addItem(spacerItem7, 0, 1, 1, 1)
        main_window.setCentralWidget(self.central_widget)

        self.retranslateUi(main_window)
        QtCore.QMetaObject.connectSlotsByName(main_window)

    def retranslateUi(self, main_window):
        _translate = QtCore.QCoreApplication.translate
        main_window.setWindowTitle(_translate("main_window", "Learning program"))
        self.tip_2.setText(_translate("main_window", "Set up new schedule:"))
        self.tip.setText(_translate("main_window", "Indicate time you spend per day (hour/day):"))
        self.btnFree.setText(_translate("main_window", "Free day"))
        self.btnLearn.setText(_translate("main_window", "Learn day"))
        self.btnRepeat.setText(_translate("main_window", "Repeat day"))
        self.tip_5.setText(_translate("main_window", "Sleep"))
        self.sleepTime_list.setItemText(0, _translate("main_window", "1"))
        self.sleepTime_list.setItemText(1, _translate("main_window", "2"))
        self.sleepTime_list.setItemText(2, _translate("main_window", "3"))
        self.sleepTime_list.setItemText(3, _translate("main_window", "4"))
        self.sleepTime_list.setItemText(4, _translate("main_window", "5"))
        self.tip_3.setText(_translate("main_window", "Learn"))
        self.learnTime_list.setItemText(0, _translate("main_window", "12"))
        self.learnTime_list.setItemText(1, _translate("main_window", "13"))
        self.learnTime_list.setItemText(2, _translate("main_window", "14"))
        self.learnTime_list.setItemText(3, _translate("main_window", "15"))
        self.tip_4.setText(_translate("main_window", "Repeat"))
        self.repeatTime_list.setItemText(0, _translate("main_window", "20"))
        self.repeatTime_list.setItemText(1, _translate("main_window", "21"))
        self.repeatTime_list.setItemText(2, _translate("main_window", "22"))
        self.repeatTime_list.setItemText(3, _translate("main_window", "23"))
        self.header.setText(_translate("main_window", "YOUR NEW SCHEDULE"))


class SubjectScreen(QtWidgets.QWidget):

    def setupUi(self, main_window):
        self.main_widget = QtWidgets.QWidget()
        self.init_widget()
        main_window.setCentralWidget(self.main_widget)
        self.retranslateUi(main_window)

    def init_widget(self):
        mainLayout = QtWidgets.QVBoxLayout(self.main_widget)
        activeLayout = QtWidgets.QHBoxLayout()
        mainLayout.addSpacing(20)  # Top space
        activeLayout.addSpacing(20)  # Left space

        contentLayout = QtWidgets.QVBoxLayout()  # Create content layout
        self.init_content(contentLayout)  # Filling up content layout
        activeLayout.addLayout(contentLayout)
        activeLayout.addSpacing(20)  # Right space
        mainLayout.addLayout(activeLayout)
        mainLayout.addSpacing(20)  # Bottom space
        self.main_widget.setLayout(mainLayout)

    def init_content(self, layout):
        # Icons
        nextIcon = QtGui.QIcon()
        nextIcon.addPixmap(QtGui.QPixmap("icons/angle-right-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        backIcon = QtGui.QIcon()
        backIcon.addPixmap(QtGui.QPixmap("icons/angle-left-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        # Fonts
        btnFont = QtGui.QFont()
        btnFont.setPointSize(12)
        headerFont = QtGui.QFont()
        headerFont.setPointSize(20)
        tipFont = QtGui.QFont()
        tipFont.setPointSize(12)
        listFont = QtGui.QFont()
        listFont.setPointSize(15)

        # Init page bar
        page_bar = QtWidgets.QProgressBar()
        page_bar.setObjectName("page_bar")
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(page_bar.sizePolicy().hasHeightForWidth())
        page_bar.setSizePolicy(sizePolicy)
        page_bar.setMinimumSize(QtCore.QSize(0, 4))
        page_bar.setProperty("value", 0)
        page_bar.setTextVisible(False)
        self.page_bar = page_bar
        layout.addWidget(self.page_bar)  # Adding "page bar" in to layout

        # Init header
        header = QtWidgets.QLabel()
        header.setObjectName("header")
        header.setMinimumSize(QtCore.QSize(0, 60))
        header.setFont(headerFont)
        self.header = header
        layout.addWidget(self.header)

        # Init variables tip
        tip = QtWidgets.QLabel()
        tip.setObjectName("tip")
        tip.setFont(tipFont)
        tip.setAlignment(QtCore.Qt.AlignBottom | QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft)
        self.tip = tip
        layout.addWidget(self.tip)

        # Init variables layout

        # Init

        # # Init subject list
        # subject_list = QtWidgets.QComboBox()
        # subject_list.setObjectName("subject_list")
        # subject_list.setMinimumSize(QtCore.QSize(200, 40))
        # subject_list.setFont(listFont)
        # # Flags for list
        # flags = subject_list.view().window().windowFlags() | Qt.Popup | Qt.FramelessWindowHint | Qt.NoDropShadowWindowHint
        # subject_list.view().window().setWindowFlags(flags)
        # self.subject_list = subject_list
        # layout.addWidget(self.subject_list)
        # layout.addStretch(1)

        # Creating functional layout with "back" and "next" buttons
        functionalLayout = QtWidgets.QHBoxLayout()
        btnBack = QtWidgets.QPushButton()
        btnBack.setObjectName("btnBack")
        btnBack.setMinimumSize(60, 60)
        btnBack.setMaximumSize(60, 60)
        btnBack.setIcon(backIcon)
        btnNext = QtWidgets.QPushButton()
        btnNext.setObjectName("btnNext")
        btnNext.setMinimumSize(60, 60)
        btnNext.setMaximumSize(60, 60)
        btnNext.setIcon(nextIcon)

        self.btnBack = btnBack
        self.btnNext = btnNext
        functionalLayout.addWidget(self.btnBack)  # Adding "continue" button in to layout
        functionalLayout.addWidget(self.btnNext)  # Adding "create" button in to layout

        layout.addLayout(functionalLayout)  # Adding functional layout in to contentLayout

    def retranslateUi(self, main_window):
        _translate = QtCore.QCoreApplication.translate
        main_window.setWindowTitle(_translate("main_window", "Learning program"))
        self.header.setText(_translate("main_window", "CHOOSE YOUR SUBJECT"))
        self.tip.setText(_translate("main_window", "Indicate subject you want to learn:"))
